stages:
  data_ingestion:
    cmd: python src/generic_classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/generic_classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/real_or_fake_face


  prepare_base_model:
    cmd: python src/generic_classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/generic_classifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/generic_classifier/pipeline/stage_03_training.py
    deps:
      - src/generic_classifier/pipeline/stage_03_training.py
      - src/generic_classifier/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/real_or_fake_face
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.keras


  

  evaluation:
    cmd: python src/generic_classifier/pipeline/stage_04_evaluation.py
    deps:
      - src/generic_classifier/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/real_or_fake_face
      - artifacts/training/model.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false